version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: udacity_de

volumes:
  db-data:
