version: '3.1'

services:
  relational-db:
    image: postgres
    restart: always
    volumes:
      - pg-data:/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: udacity_de

  nosql-db:
    image: cassandra
    restart: always
    volumes:
      - cassandra-data:/var/lib/cassandra
    ports:
      - "9042:9042"


volumes:
  pg-data:
  cassandra-data:
